data:
  # Format must be [[latitiude, longitude], ... ]
  coordinates:
    [[52.237049, 21.017532]]
  radius: 10000

time:
  start: 2022-01-01 00:00:00
  end: 2025-01-31 00:00:00
  rollup: daily # hourly|daily|yearly

paging:
  limit: 1000

# Local outputs (what you write to disk)
outputs:
  dir: data/raw
  files:
    openaq:
      locations: locations_dataset.csv
      sensors_metadata: sensors_metadata.csv
      sensors_measurements: sensors_measurement.csv
    meteostat:
      weather_daily: weather_daily.csv

# Source-specific config (what you request / how you call APIs)
sources:
  openaq:
    state:
      last_added_sensor_id: null
      sensors_to_skip: []
  meteostat:
    units: metric
    model: false