openaq:
  coordinates:
    latitude: 52.237049
    longitude: 21.017532
  radius: 10000
  daterange:  # Date range is interpreted as UTC
    min: 2025-01-01 00:00:00
    max: 2025-01-10 00:00:00
  limit: 1000 # Max amount is 1000
  rollup: hourly # daily, yearly, hourly
  outputs:
    locations: locations_dataset.csv
    sensors_metadata: sensors_metadata.csv
    sensors_measurement: sensors_measurement.csv