openaq:
  coordinates:
    latitude: 52.237049
    longitude: 21.017532
  radius: 10000
  daterange:
    min: 2025-01-01 00:00:00
    max: 2025-01-31 00:00:00
  limit: 10
  outputs:
    locations: location_dataset.csv
    sensors: sensor_dataset.csv